name: libraryapp
description: A new Flutter project.

dependencies:
  image_picker: "^0.1.1"
  shared_preferences: "0.2.4+1"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/fox.jpg
    - images/guy1.jpg
    - images/guy2.jpg
    - images/girl1.jpg
    - images/gamenight.jpg
    - images/knittingnight.jpg
    - images/movenight.jpg
    - images/girl2.jpg
    - images/guy3.jpg
    - images/guy4.png
    - images/guy5.jpg
    - images/puzzle.png
    - images/puzzles.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
